import re
from typing import Dict, Any, List
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser, JsonOutputParser
from src.state import ResumeState
from langchain_core.runnables import RunnableConfig
from pydantic import BaseModel, Field


def basic_pii_scrub(text: str) -> str:
    """ Regex based cleaning for email and phone numbers. """
    if not isinstance(text, str):
        return ""
    
    # Clean spurious text generated by LLM when creating synthetic CVs
    text = re.sub(r"```markdown", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text)
    
    # Remove email and phone numer
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '[EMAIL_REDACTED]', text)
    text = re.sub(r'\b(?:\+?61|0)[2-478](?:[ -]?[0-9]){8}\b', '[PHONE_REDACTED]', text) 
    
    # Convert triple newlines to double newlines to keep markdown chunks consistent
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def run_anonymiser_agent(state: ResumeState, config: RunnableConfig = None) -> Dict[str, Any]:
    """
    Code to use LLM to remove personal information
    """
    
    llm = ChatOllama(model="llama3.1:8b", temperature=0.0)
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are an expert AI redaction engine. Your job is to remove any indicators of "
            "race, gender, age, location, or socioeconomic background from the provided CV text.\n\n"
            "STRICT RULES:\n"
            "1. Remove specific graduation years or chronological dates that directly tip off age "
            "(e.g., transform 'Graduated in 2006 with Honors' into 'Graduated with Honors').\n"
            "2. Neutralize explicitly gendered groups or associations (e.g., convert 'Society of Women Engineers' "
            "into 'Professional Engineering Association').\n"
            "3. Swap personal candidate names or precise street directions with generic labels like [LOCATION_REDACTED].\n"
            "4. CRITICAL: Never modify technical metrics, tech-stack keywords, architectural scopes, or tool names.\n"
            "Retain the exact Markdown formatting syntax. Output ONLY the polished, scrubbed text."
        )),
        ("human", "{text}")
    ])
    
    chain = prompt | llm | StrOutputParser()
    
    # pre-clean the data
    pre_cleaned = basic_pii_scrub(state["raw_resume"])
    
    # LLM based redaction
    anonymized_output = chain.invoke(
        {"text": pre_cleaned},
        config = config
        )
    
    return {
        "clean_resume": pre_cleaned,
        "anonymized_resume": anonymized_output
    }

## Code Block to define agent to parse job description requirements into a json format
class JobRequirements(BaseModel):
    role_title: str = Field(description="The official title of the position")
    # Remove non essential information from JD. 
    # This information will be used for vector db search to retrieve relevant chunks
    dense_search_string: str = Field(
        description="A dense, natural-language paragraph summarizing ONLY the technical skills, "
                    "responsibilities, and qualifications. Completely exclude company culture, "
                    "perks, boilerplate, and team structure."
    )
    # Structured fields to compare shortlisted CVs using a LLM
    must_have_skills: List[str] = Field(description="Strictly mandatory technical skills, frameworks, or languages")
    nice_to_have_skills: List[str] = Field(description="Preferred or optional technical skills")
    years_experience: str = Field(description="The required years of experience. Return 'Not Specified' if missing.")
    core_responsibilities: List[str] = Field(description="3 to 5 brief bullet points summarizing the main duties")

def run_jd_extraction_agent(jd_text: str) -> Dict[str, Any]:
    """
    Analyzes a raw Job Description and extracts both a dense natural-language 
    string for vector search, and structured JSON arrays for final evaluation.
    """
    llm = ChatOllama(model="llama3.1:8b", temperature=0.0, format="json")
    parser = JsonOutputParser(pydantic_object=JobRequirements)
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are an expert technical parsing system.\n"
            "Your task is to dissect the provided Job Description into two parts:\n"
            "1. A dense, plain-text summary of the technical constraints (to be used for semantic database search).\n"
            "2. Structured lists of skills and responsibilities.\n\n"
            "CRITICAL: Strip out all marketing fluff, company history, EEO statements, and cultural perks. "
            "Focus purely on what the candidate must build, know, and execute.\n\n"
            "{format_instructions}"
        )),
        ("human", "JOB DESCRIPTION:\n{jd_text}")
    ])
    
    prompt = prompt.partial(format_instructions=parser.get_format_instructions())
    chain = prompt | llm | parser
    
    return chain.invoke({"jd_text": jd_text})


## Code block to define agent to parse anonymised CV into a json format for comparison.
class CandidateProfile(BaseModel):
    total_years_experience: str = Field(description="Total years of professional experience. Calculate this if a summary states it, or estimate based on dates.")
    technical_skills: List[str] = Field(description="Explicit programming languages, databases, tools, and technical frameworks used.")
    domain_knowledge: List[str] = Field(description="Industry-specific concepts, methodologies, or sectors (e.g., Banking, CI/CD, Agile, RAG, Regulatory Reporting).")
    key_achievements: List[str] = Field(description="Extract the top 3 to 5 measurable or highly impactful technical achievements.")

def run_resume_extraction_agent(cv_text: str) -> Dict[str, Any]:
    """
    Analyzes an anonymized resume and extracts CV information in JSON form 
    to be mapped against the JD requirements.
    """
    # Force the local Llama 3 model to only output valid JSON
    llm = ChatOllama(model="llama3.1:8b", temperature=0.0, format="json")
    
    # Initialize the parser with the CandidateProfile schema
    parser = JsonOutputParser(pydantic_object=CandidateProfile)
    
    # Build the extraction prompt
    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are an expert resume parsing system.\n"
            "Analyze the following resume and extract the core professional profile.\n"
            "Ignore marketing fluff and focus on concrete engineering skills, tools, and measurable achievements.\n\n"
            "{format_instructions}"
        )),
        ("human", "RESUME TEXT:\n{cv_text}")
    ])
    
    # Inject the parser's instructions into the prompt template
    prompt = prompt.partial(format_instructions=parser.get_format_instructions())
    
    chain = prompt | llm | parser
    
    return chain.invoke({"cv_text": cv_text})